# Generated by Django 4.1.3 on 2022-11-12 16:27

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(null=True, upload_to='profile/', verbose_name='profile image')),
                ('about', ckeditor.fields.RichTextField(blank=True, verbose_name='about me')),
                ('social_media', ckeditor.fields.RichTextField(blank=True, verbose_name='social media links')),
                ('contacts', ckeditor.fields.RichTextField(blank=True, verbose_name='contacts')),
                ('skills', ckeditor.fields.RichTextField(blank=True, verbose_name='skills')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('body', ckeditor.fields.RichTextField(verbose_name='body')),
                ('from_date', models.DateField(verbose_name='from date')),
                ('to_date', models.DateField(auto_now=True, verbose_name='to date')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
