# Generated by Django 4.1.3 on 2022-11-12 16:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='blogs/assets/')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
                ('body', ckeditor.fields.RichTextField(verbose_name='body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date uploaded')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date edited')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
