# Generated by Django 4.1.3 on 2022-11-13 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogassets',
            options={'verbose_name': 'blog assets', 'verbose_name_plural': 'blog assets'},
        ),
    ]
