# Generated by Django 4.1.3 on 2022-11-13 12:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
                ('body', ckeditor.fields.RichTextField(verbose_name='body')),
                ('image', models.ImageField(upload_to='news/images/', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date uploaded')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date edited')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
